var Global = {
    urlApi: "https://apitechriders.azurewebsites.net/",
    token: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VyRGF0YSI6IntcIklkVXN1YXJpb1wiOjI3LFwiTm9tYnJlXCI6XCJ0ZXN0XCIsXCJBcGVsbGlkb3NcIjpcInRlc3RcIixcIkVtYWlsXCI6XCJ0ZXN0QGdtYWlsLmNvbVwiLFwiVGVsZWZvbm9cIjpcIjQ1Njc4WFwiLFwiTGlua2VkSW5cIjpcImxpbmtlZGluLmNvbVwiLFwiUGFzc3dvcmRcIjpcIjEyMzQ1XCIsXCJJZFJvbGVcIjoxLFwiSWRQcm92aW5jaWFcIjoyNyxcIklkRW1wcmVzYUNlbnRyb1wiOm51bGwsXCJFc3RhZG9cIjowfSIsIm5iZiI6MTcwNTIzODY5OSwiZXhwIjoxNzA1MjQwNDk5LCJpc3MiOiJodHRwczovL2xvY2FsaG9zdDo3MDMyLyIsImF1ZCI6IkFwaVRlY2hSaWRlcnNDb3JlT0F1dGgifQ.FGXbjeAo56g-RkkIMx1Svilcm3_I4K936Q1THkM2GRo" 
}
export default Global;