var Global = {
    urlApi: "https://apitechriders.azurewebsites.net/",
    token: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VyRGF0YSI6IntcIklkVXN1YXJpb1wiOjI3LFwiTm9tYnJlXCI6XCJ0ZXN0XCIsXCJBcGVsbGlkb3NcIjpcInRlc3RcIixcIkVtYWlsXCI6XCJ0ZXN0QGdtYWlsLmNvbVwiLFwiVGVsZWZvbm9cIjpcIjQ1Njc4WFwiLFwiTGlua2VkSW5cIjpcImxpbmtlZGluLmNvbVwiLFwiUGFzc3dvcmRcIjpcIjEyMzQ1XCIsXCJJZFJvbGVcIjoxLFwiSWRQcm92aW5jaWFcIjoyNyxcIklkRW1wcmVzYUNlbnRyb1wiOm51bGwsXCJFc3RhZG9cIjowfSIsIm5iZiI6MTcwNTIyNjY3OSwiZXhwIjoxNzA1MjI4NDc5LCJpc3MiOiJodHRwczovL2xvY2FsaG9zdDo3MDMyLyIsImF1ZCI6IkFwaVRlY2hSaWRlcnNDb3JlT0F1dGgifQ.i6IE366tKWZGLFeHW3iKdmi8NAgGk4xQMCKT-0XS62s" 
}
export default Global;